In [ ]:
import pandas as pd

acs_data = pd.read_csv('/content/acs2017_census_tract_data.csv')

acs_data = acs_data[['County', 'TotalPop', 'Poverty', 'IncomePerCap']]

county_info = acs_data.groupby('County').agg({
    'TotalPop': 'sum',
    'Poverty': 'mean',
    'IncomePerCap': 'mean'
}).reset_index()

county_info['ID'] = county_info.index

county_info.rename(columns={
    'TotalPop': 'Population',
    'Poverty': '%poverty',
    'IncomePerCap': 'PerCapitaIncome'
}, inplace=True)

print(county_info.head())

specific_counties = county_info[county_info['County'].isin([
    'Loudoun County, Virginia', 'Washington County, Oregon',
    'Harlan County, Kentucky', 'Malheur County, Oregon'
])]

print(specific_counties)

             County  Population   %poverty  PerCapitaIncome  ID
0  Abbeville County       24788  22.183333     19402.833333   0
1     Acadia Parish       62607  21.933333     21454.250000   1
2   Accomack County       32840  20.112500     24769.750000   2
3        Ada County      435117  12.608475     32672.661017   3
4      Adair County       74069  25.909091     19711.409091   4
Empty DataFrame
Columns: [County, Population, %poverty, PerCapitaIncome, ID]
Index: []

In [ ]:
import pandas as pd

acs_data = pd.read_csv('/content/acs2017_census_tract_data.csv')
required_columns = ['County', 'State', 'TotalPop', 'IncomePerCap', 'Poverty']
acs_data_filtered = acs_data[required_columns].copy()
acs_data_filtered['ID'] = range(len(acs_data_filtered))
aggregated_data = acs_data_filtered.groupby(['County', 'State']).agg({'TotalPop': 'sum', 'IncomePerCap': 'mean', 'Poverty': 'mean'})
county_info = aggregated_data.reset_index()
county_info.rename(columns={'County': 'county', 'TotalPop': 'Population', 'IncomePerCap': 'PerCapitaIncome'}, inplace=True)
county_info['ID'] = county_info.index + 1

county_info

,county,State,Population,PerCapitaIncome,Poverty,ID
0,Abbeville County,South Carolina,24788,19402.833333,22.183333,1
1,Acadia Parish,Louisiana,62607,21454.250000,21.933333,2
2,Accomack County,Virginia,32840,24769.750000,20.112500,3
3,Ada County,Idaho,435117,32672.661017,12.608475,4
4,Adair County,Iowa,7192,28840.666667,9.566667,5
...,...,...,...,...,...,...
3215,Yuma County,Arizona,204281,21479.641509,19.357692,3216
3216,Yuma County,Colorado,10109,24841.000000,14.350000,3217
3217,Zapata County,Texas,14415,17884.333333,32.566667,3218
3218,Zavala County,Texas,12152,12660.250000,41.375000,3219
3219,Ziebach County,South Dakota,2837,13461.000000,43.100000,3220

In [ ]:
county_inputs = ["Loudoun County, Virginia", "Washington County, Oregon", "Harlan County, Kentucky", "Malheur County, Oregon"]
county_details_list = []

for input_county in county_inputs:
    county_name, state_name = input_county.split(", ")
    details = county_info[(county_info['county'] == county_name) & (county_info['State'] == state_name)]
    county_details_list.append(details)

county_details = pd.concat(county_details_list, ignore_index=True)
print(county_details)

              county     State  Population  PerCapitaIncome    Poverty    ID
0     Loudoun County  Virginia      374558     50391.015625   3.884375  1760
1  Washington County    Oregon      572071     34970.817308  10.446154  3047
2      Harlan County  Kentucky       27548     16010.363636  33.318182  1235
3     Malheur County    Oregon       30421     17966.428571  24.414286  1823

In [ ]:
covid_data['ID'] = covid_data['county'] + '_' + covid_data['state']
covid_data['ID'] = pd.factorize(covid_data['ID'])[0] + 1

covid_data

,date,county,state,fips,cases,deaths,Month,Year,ID
0,2020-01-21,snohomish,washington,53061.0,1,0.0,1,2020,1
1,2020-01-22,snohomish,washington,53061.0,1,0.0,1,2020,1
2,2020-01-23,snohomish,washington,53061.0,1,0.0,1,2020,1
3,2020-01-24,cook,illinois,17031.0,1,0.0,1,2020,2
4,2020-01-24,snohomish,washington,53061.0,1,0.0,1,2020,1
...,...,...,...,...,...,...,...,...,...
1050253,2021-02-20,sweetwater,wyoming,56037.0,3645,34.0,2,2021,1357
1050254,2021-02-20,teton,wyoming,56039.0,3318,9.0,2,2021,640
1050255,2021-02-20,uinta,wyoming,56041.0,2024,12.0,2,2021,2305
1050256,2021-02-20,washakie,wyoming,56043.0,876,26.0,2,2021,1784
1050257,2021-02-20,weston,wyoming,56045.0,619,5.0,2,2021,3076

In [ ]:
covid_data['date'] = pd.to_datetime(covid_data['date'], format='%Y-%m-%d')

covid_data['month'] = covid_data['date'].dt.to_period('M')
covid_data

,date,county,state,fips,cases,deaths,Month,Year,ID,month
0,2020-01-21,snohomish,washington,53061.0,1,0.0,1,2020,1,2020-01
1,2020-01-22,snohomish,washington,53061.0,1,0.0,1,2020,1,2020-01
2,2020-01-23,snohomish,washington,53061.0,1,0.0,1,2020,1,2020-01
3,2020-01-24,cook,illinois,17031.0,1,0.0,1,2020,2,2020-01
4,2020-01-24,snohomish,washington,53061.0,1,0.0,1,2020,1,2020-01
...,...,...,...,...,...,...,...,...,...,...
1050253,2021-02-20,sweetwater,wyoming,56037.0,3645,34.0,2,2021,1357,2021-02
1050254,2021-02-20,teton,wyoming,56039.0,3318,9.0,2,2021,640,2021-02
1050255,2021-02-20,uinta,wyoming,56041.0,2024,12.0,2,2021,2305,2021-02
1050256,2021-02-20,washakie,wyoming,56043.0,876,26.0,2,2021,1784,2021-02
1050257,2021-02-20,weston,wyoming,56045.0,619,5.0,2,2021,3076,2021-02

In [ ]:
covid_data_monthly = covid_data.groupby(['ID', 'month']).agg({
    'cases': 'sum',
    'deaths': 'sum',
    'county': 'first'
}).reset_index()

covid_data_monthly['ID'] = range(1, len(covid_data_monthly) + 1)
covid_data_monthly = covid_data_monthly[['ID', 'month', 'cases', 'deaths', 'county']].copy()

covid_data_monthly.columns = ['ID', 'Month', 'cases', 'deaths', 'county']

covid_data_monthly

          ID    Month  cases  deaths     county
0          1  2020-01     11     0.0  snohomish
1          2  2020-02     31     0.0  snohomish
2          3  2020-03  11076   246.0  snohomish
3          4  2020-04  58740  2366.0  snohomish
4          5  2020-05  94534  3898.0  snohomish
...      ...      ...    ...     ...        ...
37252  37253  2020-11      1     0.0    unknown
37253  37254  2020-12     22     0.0    kalawao
37254  37255  2021-01     31     0.0    kalawao
37255  37256  2021-02     20     0.0    kalawao
37256  37257  2021-01    998     0.0    unknown

[37257 rows x 5 columns]

In [ ]:
selected_months = ['2020-08', '2021-01', '2021-02']
selected_county = 'Malheur County'
covid_report = covid_data_monthly[(covid_data_monthly['county'] == selected_county) &
                              (covid_data_monthly['Month'].astype(str).isin(selected_months))]

print(covid_report)

Empty DataFrame
Columns: [ID, Month, cases, deaths, county]
Index: []

In [ ]:
covid_summary = (covid_data_monthly.groupby("ID").agg({"cases": "sum", "deaths": "sum"}).reset_index())
covid_summary.rename(columns={"cases": "TotalCases", "deaths": "TotalDeaths"}, inplace=True)
covid_summary = pd.merge(covid_summary, county_info, how="left", on="ID")
covid_summary["TotalCasesPer100K"] = round((covid_summary["TotalCases"]) / (covid_summary["Population"] / 100000), 2)
covid_summary["TotalDeathsPer100K"] = round((covid_summary["TotalDeaths"]) / (covid_summary["Population"] / 100000), 2)
display(covid_summary)

,ID,TotalCases,TotalDeaths,county,State,Population,PerCapitaIncome,Poverty,TotalCasesPer100K,TotalDeathsPer100K
0,1,11,0.0,Abbeville County,South Carolina,24788.0,19402.833333,22.183333,44.38,0.00
1,2,31,0.0,Acadia Parish,Louisiana,62607.0,21454.250000,21.933333,49.52,0.00
2,3,11076,246.0,Accomack County,Virginia,32840.0,24769.750000,20.112500,33727.16,749.09
3,4,58740,2366.0,Ada County,Idaho,435117.0,32672.661017,12.608475,13499.82,543.76
4,5,94534,3898.0,Adair County,Iowa,7192.0,28840.666667,9.566667,1314432.70,54199.11
...,...,...,...,...,...,...,...,...,...,...
37252,37253,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37253,37254,22,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37254,37255,31,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37255,37256,20,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37256,37257,998,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
counties = [('Washington County', 'Oregon'), ('Malheur County', 'Oregon'), ('Loudoun County', 'Virginia'), ('Harlan County', 'Kentucky')]

filtered_df = covid_summary[
    (covid_summary['county'].isin([county[0] for county in counties])) &
    (covid_summary['State'].isin([county[1] for county in counties]))
]

poverty_percentage = filtered_df[['county', 'State', 'Poverty']]
total_cases_per_100k = filtered_df[['county', 'State', 'TotalCasesPer100K']]

print("Poverty Percentage:")
print(poverty_percentage)
print("\nTotal Cases per 100K:")
print(total_cases_per_100k)

Poverty Percentage:
                 county     State    Poverty
1234      Harlan County  Kentucky  33.318182
1759     Loudoun County  Virginia   3.884375
1822     Malheur County    Oregon  24.414286
3035  Washington County  Kentucky  16.900000
3046  Washington County    Oregon  10.446154
3053  Washington County  Virginia  14.715385

Total Cases per 100K:
                 county     State  TotalCasesPer100K
1234      Harlan County  Kentucky         1671979.82
1759     Loudoun County  Virginia            3086.84
1822     Malheur County    Oregon          542792.81
3035  Washington County  Kentucky          178864.91
3046  Washington County    Oregon           61741.46
3053  Washington County  Virginia              55.09

In [ ]:
oregon_county = covid_summary[covid_summary['State'] == 'Oregon']
print(oregon_county)

        ID  TotalCases  TotalDeaths             county   State  Population  \
126    127      176630       7094.0       Baker County  Oregon     15980.0
197    198      269042       2377.0      Benton County  Oregon     88249.0
533    534       64549       2655.0   Clackamas County  Oregon    399962.0
558    559      165400       8893.0     Clatsop County  Oregon     38021.0
631    632        9177        720.0    Columbia County  Oregon     50207.0
656    657       25645        265.0        Coos County  Oregon     62921.0
697    698     1099390      19381.0       Crook County  Oregon     21717.0
718    719      294898       2637.0       Curry County  Oregon     22377.0
796    797         455         21.0   Deschutes County  Oregon    175321.0
839    840      513374       8400.0     Douglas County  Oregon    107576.0
1068  1069     1247029      27789.0     Gilliam County  Oregon      1910.0
1115  1116       11712         93.0       Grant County  Oregon      7209.0
1238  1239     1876864      22827.0      Harney County  Oregon      7195.0
1320  1321       19490        369.0  Hood River County  Oregon     22938.0
1415  1416      347301      12011.0     Jackson County  Oregon    212070.0
1453  1454      125321       2101.0   Jefferson County  Oregon     22707.0
1493  1494      146281       6744.0   Josephine County  Oregon     84514.0
1559  1560      594520      20882.0     Klamath County  Oregon     66018.0
1608  1609       53869        409.0        Lake County  Oregon      7807.0
1626  1627       24937        776.0        Lane County  Oregon    363471.0
1720  1721         707         29.0     Lincoln County  Oregon     47307.0
1731  1732      985452      14914.0        Linn County  Oregon    121074.0
1822  1823      165123       3872.0     Malheur County  Oregon     30421.0
1848  1849      394112       6060.0      Marion County  Oregon    330453.0
2070  2071        7148        145.0      Morrow County  Oregon     11153.0
2078  2079      500621       4240.0   Multnomah County  Oregon    788459.0
2359  2360        8401        241.0        Polk County  Oregon     79666.0
2671  2672        2448         30.0     Sherman County  Oregon      1635.0
2860  2861        9148         17.0   Tillamook County  Oregon     25840.0
2919  2920     1823532      16315.0    Umatilla County  Oregon     76736.0
2933  2934        5862        454.0       Union County  Oregon     25810.0
2994  2995       43886       1044.0     Wallowa County  Oregon      6864.0
3021  3022       20054        524.0       Wasco County  Oregon     25687.0
3046  3047      353205       5844.0  Washington County  Oregon    572071.0
3109  3110     1327277      18188.0     Wheeler County  Oregon      1415.0
3195  3196       34918        380.0     Yamhill County  Oregon    102366.0

      PerCapitaIncome    Poverty  TotalCasesPer100K  TotalDeathsPer100K
126      25706.833333  15.000000         1105319.15            44392.99
197      29926.000000  23.644444          304866.91             2693.51
533      37502.712500   9.320000           16138.78              663.81
558      28357.363636  12.481818          435022.75            23389.71
631      28109.700000  12.530000           18278.33             1434.06
656      26488.307692  17.415385           40757.46              421.16
697      23958.500000  15.050000         5062347.47            89243.45
718      26899.200000  16.300000         1317862.09            11784.42
796      31834.375000  12.208333             259.52               11.98
839      25208.545455  16.731818          477219.83             7808.43
1068     24178.000000   9.900000        65289476.44          1454921.47
1115     23855.000000  15.850000          162463.59             1290.05
1238     25174.500000  16.300000        26085670.60           317261.99
1320     29178.000000  12.150000           84968.18             1608.68
1415     27328.780488  17.882927          163767.15             5663.70
1453     22689.666667  20.316667          551904.70             9252.65
1493     24179.062500  19.131250          173084.93             7979.74
1559     23712.400000  18.930000          900542.28            31630.77
1608     21121.500000  19.200000          690008.97             5238.89
1626     27546.220930  18.529070            6860.79              213.50
1720     26807.411765  17.623529            1494.49               61.30
1731     24452.714286  16.923810          813925.37            12318.09
1822     17966.428571  24.414286          542792.81            12728.05
1848     25903.862069  15.329310          119264.16             1833.85
2070     23171.500000  13.450000           64090.38             1300.10
2078     36739.558824  15.730588           63493.60              537.76
2359     24633.916667  18.641667           10545.28              302.51
2671     34226.000000  13.700000          149724.77             1834.86
2860     25805.750000  15.437500           35402.48               65.79
2919     23200.466667  16.520000         2376370.93            21261.21
2933     26508.875000  17.425000           22712.13             1759.01
2994     26943.000000  14.400000          639364.80            15209.79
3021     25089.750000  13.037500           78070.62             2039.94
3046     34970.817308  10.446154           61741.46             1021.55
3109     21268.000000  20.600000        93800494.70          1285371.02
3195     28578.882353  13.935294           34110.94              371.22

In [ ]:
analysis_1a = oregon_county['TotalCases'].corr(oregon_county['Poverty'])
print(f"Correlation between % poverty and COVID total cases in Oregon counties: {analysis_1a}")
analysis_1b = oregon_county['TotalDeaths'].corr(oregon_county['Poverty'])
print(f"Correlation between % poverty and COVID total deaths in Oregon counties: {analysis_1b}")
analysis_1c = oregon_county['TotalCases'].corr(oregon_county['PerCapitaIncome'])
print(f"Correlation between Per Capita Income and COVID total cases in Oregon counties: {analysis_1c}")
analysis_1d = oregon_county['TotalDeaths'].corr(oregon_county['PerCapitaIncome'])
print(f"Correlation between Per Capita Income and COVID total deaths in Oregon counties: {analysis_1d}")

Correlation between % poverty and COVID total cases in Oregon counties: 0.05448687198634776
Correlation between % poverty and COVID total deaths in Oregon counties: -0.003927649458842
Correlation between Per Capita Income and COVID total cases in Oregon counties: -0.2557187510018219
Correlation between Per Capita Income and COVID total deaths in Oregon counties: -0.2878717772723963

In [ ]:
r2 = covid_summary['TotalDeaths'].corr(covid_summary['Poverty'])
print(r2)

0.00988447825942164

In [ ]:
r2 = covid_summary['TotalCases'].corr(covid_summary['PerCapitaIncome'])
print(r2)

-0.02544712849260708

In [ ]:
r2 = covid_summary['TotalDeaths'].corr(covid_summary['PerCapitaIncome'])
print(r2)

-0.01255471625709621